# Generated by Django 3.0.7 on 2020-06-11 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'BatteryType',
                'verbose_name_plural': 'BatteryTypes',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(null=True)),
                ('battery_count', models.IntegerField(null=True)),
                ('wireless', models.BooleanField()),
                ('return_date', models.DateField(null=True)),
                ('battery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapi.BatteryType')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EquipmentType',
                'verbose_name_plural': 'EquipmentTypes',
            },
        ),
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
                ('indoor', models.BooleanField(null=True)),
                ('date_scheduled', models.DateTimeField(null=True)),
                ('charge', models.FloatField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapi.Client')),
            ],
            options={
                'verbose_name': 'Photoshoot',
                'verbose_name_plural': 'Photoshoots',
            },
        ),
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'RentalHouse',
                'verbose_name_plural': 'RentalHouses',
            },
        ),
        migrations.CreateModel(
            name='PhotoshootStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Employee')),
                ('photoshoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Photoshoot')),
            ],
            options={
                'verbose_name': 'PhotoshootStaff',
                'verbose_name_plural': 'PhotoshootStaffs',
            },
        ),
        migrations.CreateModel(
            name='PhotoshootNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Employee')),
                ('photoshoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Photoshoot')),
            ],
            options={
                'verbose_name': 'PhotoshootNote',
                'verbose_name_plural': 'PhotoshootNotes',
            },
        ),
        migrations.CreateModel(
            name='PhotoshootEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Equipment')),
                ('photoshoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Photoshoot')),
            ],
            options={
                'verbose_name': 'PhotoshootEquipment',
                'verbose_name_plural': 'PhotoshootEquipments',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapi.EquipmentType'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backendapi.RentalHouse'),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Employee')),
            ],
            options={
                'verbose_name': 'ClientNote',
                'verbose_name_plural': 'ClientNotes',
            },
        ),
    ]
